name: Result Service CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  result-service:
    name: Result Service CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Install dependencies
      - name: Install Node dependencies
        run: npm install
        working-directory: result

      # Lint
      - name: Run ESLint check
        run: |
          npm install eslint eslint-plugin-security
          npx eslint . || true

      # SCA
      - name: Run SCA (Trivy)
        uses: aquasecurity/trivy-action@master
        continue-on-error: true
        with:
          scan-type: fs
          scan-ref: .
          format: table
          severity: HIGH,CRITICAL
          ignore-unfixed: true

      # SAST (ESLint security plugin)
      - name: Run SAST (ESLint security)
        run: |
          npm install eslint eslint-plugin-security
          npx eslint . || true

      # Unit tests
      - name: Run Unit Tests
        run: npm test || true

      # Docker build & push
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: result
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/result-find-your-bias:${{ github.sha }}

      # # DAST
      # - name: Run DAST (OWASP ZAP)
      #   uses: zaproxy/action-full-scan@v0.10.0
      #   continue-on-error: true
      #   with:
      #     target: "http://localhost:80"

      - name: Update deployment manifest
        # ADDED: This step updates the image tag in your deployment file.
        # Assumes your file is located at 'kubernetes/deployment.yaml'.
        run: |
          sed -i "s|image: .*|image: deadvexon/result-find-your-bias:${{ github.sha }}|g" k8s-specifications/result-deployment.yaml
  
      - name: Commit and push manifest changes
        # ADDED: This step commits the updated manifest file back to your main branch.
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add k8s-specifications/result-deployment.yaml
          git diff --staged --quiet || git commit -m "CI: Update image tag to ${{ github.sha }}"
          git push